// Fake data for MVP demo
import { User, Carrier, Vehicle, TransportRequest, Offer } from './types';

// Users
export const users: User[] = [
  {
    id: '1',
    email: 'jan.kowalski@example.com',
    firstName: 'Jan',
    lastName: 'Kowalski',
    phone: '+48 123 456 789',
    role: 'passenger',
    emailVerified: true,
    phoneVerified: false,
  },
  {
    id: '2',
    email: 'anna.nowak@example.com',
    firstName: 'Anna',
    lastName: 'Nowak',
    phone: '+48 987 654 321',
    role: 'passenger',
    emailVerified: false,
    phoneVerified: false,
  },
  {
    id: '3',
    email: 'transport@fast.pl',
    firstName: 'Michał',
    lastName: 'Wiśniewski',
    phone: '+48 555 123 456',
    role: 'carrier',
    emailVerified: true,
    phoneVerified: true,
  },
  {
    id: '4',
    email: 'kontakt@busline.pl',
    firstName: 'Piotr',
    lastName: 'Zieliński',
    phone: '+48 555 789 012',
    role: 'carrier',
    emailVerified: true,
    phoneVerified: false,
  },
  {
    id: '5',
    email: 'biuro@ecotransport.pl',
    firstName: 'Katarzyna',
    lastName: 'Kowalczyk',
    phone: '+48 555 345 678',
    role: 'carrier',
    emailVerified: false,
    phoneVerified: true,
  },
];

// Carriers
export const carriers: Carrier[] = [
  {
    id: 'c1',
    userId: '3',
    companyName: 'Fast Transport',
    rating: 4.8,
    reviewCount: 142,
    description: 'Profesjonalny transport grupowy od 2010 roku. Nowoczesna flota, doświadczeni kierowcy.',
    logo: '🚐',
  },
  {
    id: 'c2',
    userId: '4',
    companyName: 'BusLine Premium',
    rating: 4.9,
    reviewCount: 203,
    description: 'Komfortowe busy i autobusy. Specjalizujemy się w wyjazdach firmowych i wycieczkach.',
    logo: '🚌',
  },
  {
    id: 'c3',
    userId: '5',
    companyName: 'EcoTransport',
    rating: 4.6,
    reviewCount: 87,
    description: 'Ekologiczny transport - elektryczne i hybrydowe pojazdy.',
    logo: '🌱',
  },
];

// Vehicles
export const vehicles: Vehicle[] = [
  {
    id: 'v1',
    carrierId: 'c1',
    type: 'minibus',
    brand: 'Mercedes',
    model: 'Sprinter',
    capacity: 19,
    features: ['Klimatyzacja', 'WiFi', 'USB', 'Bagażnik'],
    images: [],
  },
  {
    id: 'v2',
    carrierId: 'c1',
    type: 'van',
    brand: 'Volkswagen',
    model: 'Crafter',
    capacity: 9,
    features: ['Klimatyzacja', 'Skórzane fotele'],
    images: [],
  },
  {
    id: 'v3',
    carrierId: 'c2',
    type: 'bus',
    brand: 'MAN',
    model: 'Lion Coach',
    capacity: 50,
    features: ['Klimatyzacja', 'WiFi', 'Toaleta', 'TV', 'Gniazdka 230V'],
    images: [],
  },
  {
    id: 'v4',
    carrierId: 'c2',
    type: 'minibus',
    brand: 'Ford',
    model: 'Transit',
    capacity: 16,
    features: ['Klimatyzacja', 'WiFi', 'Bagażnik'],
    images: [],
  },
  {
    id: 'v5',
    carrierId: 'c1',
    type: 'minibus',
    brand: 'Mercedes',
    model: 'Vito',
    capacity: 8,
    features: ['Klimatyzacja', 'Skórzane fotele', 'WiFi'],
    images: [],
  },
  {
    id: 'v6',
    carrierId: 'c2',
    type: 'bus',
    brand: 'Setra',
    model: 'S 516 HD',
    capacity: 53,
    features: ['Klimatyzacja', 'WiFi', 'Toaleta', 'TV', 'Gniazdka 230V', 'Lodówka', 'DVD'],
    images: [],
  },
  {
    id: 'v7',
    carrierId: 'c3',
    type: 'minibus',
    brand: 'Nissan',
    model: 'e-NV200',
    capacity: 7,
    features: ['Klimatyzacja', 'Elektryczny', 'Cichy'],
    images: [],
  },
  {
    id: 'v8',
    carrierId: 'c3',
    type: 'bus',
    brand: 'Solaris',
    model: 'Urbino Electric',
    capacity: 40,
    features: ['Klimatyzacja', 'WiFi', 'USB', '100% Elektryczny', 'Ekologiczny'],
    images: [],
  },
  {
    id: 'v9',
    carrierId: 'c1',
    type: 'bus',
    brand: 'Scania',
    model: 'Touring',
    capacity: 49,
    features: ['Klimatyzacja', 'WiFi', 'Toaleta', 'TV', 'Gniazdka', 'Bar'],
    images: [],
  },
];

// Transport Requests
export const transportRequests: TransportRequest[] = [
  {
    id: 'r1',
    userId: '1',
    status: 'active',
    from: {
      address: 'Rynek Główny 1',
      city: 'Kraków',
      coordinates: { lat: 50.0614, lng: 19.9366 },
    },
    to: {
      address: 'Stare Miasto',
      city: 'Warszawa',
      coordinates: { lat: 52.2297, lng: 21.0122 },
    },
    departureDate: new Date('2025-12-15T08:00:00'),
    returnDate: new Date('2025-12-15T18:00:00'),
    isRoundTrip: true,
    passengerCount: 25,
    luggageInfo: 'Bagaż podręczny + 1 walizka na osobę',
    specialRequirements: 'Preferowana klimatyzacja',
    budget: {
      max: 3000,
      currency: 'PLN',
    },
    viewCount: 12,
    offerCount: 3,
    createdAt: new Date('2025-11-15T10:00:00'),
    updatedAt: new Date('2025-11-15T10:00:00'),
  },
  {
    id: 'r2',
    userId: '2',
    status: 'active',
    from: {
      address: 'Port Lotniczy',
      city: 'Gdańsk',
      coordinates: { lat: 54.3520, lng: 18.6466 },
    },
    to: {
      address: 'Hotel Marina',
      city: 'Sopot',
      coordinates: { lat: 54.4419, lng: 18.5602 },
    },
    departureDate: new Date('2025-12-20T14:30:00'),
    isRoundTrip: false,
    passengerCount: 8,
    luggageInfo: 'Tylko bagaż podręczny',
    viewCount: 5,
    offerCount: 2,
    createdAt: new Date('2025-11-16T14:00:00'),
    updatedAt: new Date('2025-11-16T14:00:00'),
  },
  {
    id: 'r3',
    userId: '1',
    status: 'offers_received',
    from: {
      address: 'Dworzec PKP',
      city: 'Wrocław',
      coordinates: { lat: 51.1079, lng: 17.0385 },
    },
    to: {
      address: 'Stadion Narodowy',
      city: 'Warszawa',
      coordinates: { lat: 52.2297, lng: 21.0122 },
    },
    departureDate: new Date('2025-11-30T09:00:00'),
    isRoundTrip: false,
    passengerCount: 45,
    specialRequirements: 'Wyjazd kibicowski - potrzebny duży autobus',
    budget: {
      min: 2000,
      max: 4000,
      currency: 'PLN',
    },
    viewCount: 18,
    offerCount: 5,
    createdAt: new Date('2025-11-14T09:00:00'),
    updatedAt: new Date('2025-11-14T09:00:00'),
  },
  {
    id: 'r4',
    userId: '1',
    status: 'active',
    from: {
      address: 'Centrum Konferencyjne',
      city: 'Poznań',
      coordinates: { lat: 52.4064, lng: 16.9252 },
    },
    to: {
      address: 'Hotel Radisson',
      city: 'Zakopane',
      coordinates: { lat: 49.2992, lng: 19.9496 },
    },
    departureDate: new Date('2025-12-22T09:00:00'),
    returnDate: new Date('2025-12-24T16:00:00'),
    isRoundTrip: true,
    passengerCount: 35,
    luggageInfo: 'Bagaż + sprzęt narciarski',
    specialRequirements: 'Wyjazd integracyjny firmowy, potrzebny WiFi i ładowarki',
    budget: {
      max: 5500,
      currency: 'PLN',
    },
    viewCount: 8,
    offerCount: 4,
    createdAt: new Date('2025-11-16T11:00:00'),
    updatedAt: new Date('2025-11-16T11:00:00'),
  },
  {
    id: 'r5',
    userId: '2',
    status: 'active',
    from: {
      address: 'Lotnisko Chopina',
      city: 'Warszawa',
      coordinates: { lat: 52.1672, lng: 20.9679 },
    },
    to: {
      address: 'Centrum miasta',
      city: 'Lublin',
      coordinates: { lat: 51.2465, lng: 22.5684 },
    },
    departureDate: new Date('2025-12-18T15:00:00'),
    isRoundTrip: false,
    passengerCount: 12,
    luggageInfo: 'Walizki + bagaż podręczny',
    viewCount: 6,
    offerCount: 3,
    createdAt: new Date('2025-11-16T16:00:00'),
    updatedAt: new Date('2025-11-16T16:00:00'),
  },
  {
    id: 'r6',
    userId: '1',
    status: 'booked',
    from: {
      address: 'Dworzec Główny',
      city: 'Katowice',
    },
    to: {
      address: 'Park Rozrywki',
      city: 'Energylandia',
    },
    departureDate: new Date('2025-11-25T08:00:00'),
    returnDate: new Date('2025-11-25T20:00:00'),
    isRoundTrip: true,
    passengerCount: 28,
    luggageInfo: 'Tylko plecaki',
    specialRequirements: 'Wyjazd szkolny - dzieci w wieku 12-15 lat',
    budget: {
      max: 1800,
      currency: 'PLN',
    },
    viewCount: 15,
    offerCount: 6,
    createdAt: new Date('2025-11-10T10:00:00'),
    updatedAt: new Date('2025-11-12T14:00:00'),
  },
  {
    id: 'r7',
    userId: '2',
    status: 'active',
    from: {
      address: 'Rynek',
      city: 'Szczecin',
      coordinates: { lat: 53.4285, lng: 14.5528 },
    },
    to: {
      address: 'Marina',
      city: 'Świnoujście',
      coordinates: { lat: 53.9103, lng: 14.2472 },
    },
    departureDate: new Date('2025-12-28T10:00:00'),
    isRoundTrip: false,
    passengerCount: 20,
    specialRequirements: 'Transport dla grupy seniorów, potrzebna wygodna podróż',
    budget: {
      max: 1200,
      currency: 'PLN',
    },
    viewCount: 7,
    offerCount: 2,
    createdAt: new Date('2025-11-17T09:00:00'),
    updatedAt: new Date('2025-11-17T09:00:00'),
  },
  {
    id: 'r8',
    userId: '1',
    status: 'active',
    from: {
      address: 'Dworzec Łódź Fabryczna',
      city: 'Łódź',
      coordinates: { lat: 51.7592, lng: 19.4560 },
    },
    to: {
      address: 'Galeria Krakowska',
      city: 'Kraków',
      coordinates: { lat: 50.0677, lng: 19.9483 },
    },
    departureDate: new Date('2025-12-12T07:30:00'),
    returnDate: new Date('2025-12-12T20:00:00'),
    isRoundTrip: true,
    passengerCount: 18,
    luggageInfo: 'Bagaż podręczny',
    specialRequirements: 'Wyjazd na zakupy grupowe',
    budget: {
      max: 2200,
      currency: 'PLN',
    },
    viewCount: 9,
    offerCount: 4,
    createdAt: new Date('2025-11-18T10:00:00'),
    updatedAt: new Date('2025-11-18T10:00:00'),
  },
  {
    id: 'r9',
    userId: '2',
    status: 'active',
    from: {
      address: 'Spodek',
      city: 'Katowice',
      coordinates: { lat: 50.2649, lng: 19.0238 },
    },
    to: {
      address: 'Plaża Stogi',
      city: 'Gdańsk',
      coordinates: { lat: 54.3753, lng: 18.6889 },
    },
    departureDate: new Date('2025-12-26T06:00:00'),
    isRoundTrip: false,
    passengerCount: 42,
    luggageInfo: 'Bagaż podróżny + plecaki',
    specialRequirements: 'Wyjazd firmowy nad morze, potrzebny duży autobus',
    budget: {
      max: 4500,
      currency: 'PLN',
    },
    viewCount: 14,
    offerCount: 7,
    createdAt: new Date('2025-11-18T14:00:00'),
    updatedAt: new Date('2025-11-18T14:00:00'),
  },
  {
    id: 'r10',
    userId: '1',
    status: 'active',
    from: {
      address: 'Opera Nova',
      city: 'Bydgoszcz',
      coordinates: { lat: 53.1235, lng: 18.0084 },
    },
    to: {
      address: 'Stary Rynek',
      city: 'Poznań',
      coordinates: { lat: 52.4082, lng: 16.9335 },
    },
    departureDate: new Date('2025-12-19T14:00:00'),
    isRoundTrip: false,
    passengerCount: 15,
    luggageInfo: 'Bagaż podręczny',
    specialRequirements: 'Wyjazd kulturalny na koncert',
    budget: {
      max: 1400,
      currency: 'PLN',
    },
    viewCount: 5,
    offerCount: 2,
    createdAt: new Date('2025-11-19T09:00:00'),
    updatedAt: new Date('2025-11-19T09:00:00'),
  },
  {
    id: 'r11',
    userId: '2',
    status: 'offers_received',
    from: {
      address: 'Stare Miasto',
      city: 'Toruń',
      coordinates: { lat: 53.0138, lng: 18.5984 },
    },
    to: {
      address: 'Rynek',
      city: 'Wrocław',
      coordinates: { lat: 51.1079, lng: 17.0385 },
    },
    departureDate: new Date('2025-12-21T09:00:00'),
    returnDate: new Date('2025-12-22T18:00:00'),
    isRoundTrip: true,
    passengerCount: 30,
    luggageInfo: 'Walizki + bagaż podręczny',
    specialRequirements: 'Wyjazd studencki na konferencję',
    budget: {
      max: 3200,
      currency: 'PLN',
    },
    viewCount: 11,
    offerCount: 5,
    createdAt: new Date('2025-11-19T11:00:00'),
    updatedAt: new Date('2025-11-19T11:00:00'),
  },
];

// Offers
export const offers: Offer[] = [
  {
    id: 'o1',
    requestId: 'r1',
    carrierId: 'c1',
    vehicleId: 'v1',
    status: 'pending',
    price: 2800,
    currency: 'PLN',
    description: 'Oferujemy komfortowy transport Mercedes Sprinter (19 miejsc). Pojazd w pełni klimatyzowany z WiFi.',
    includedServices: ['WiFi', 'Klimatyzacja', 'Woda mineralna', 'Elastyczny harmonogram'],
    proposedDeparture: new Date('2025-12-15T08:00:00'),
    proposedReturn: new Date('2025-12-15T18:00:00'),
    estimatedDuration: 300,
    validUntil: new Date('2025-11-20T23:59:59'),
    createdAt: new Date('2025-11-15T12:00:00'),
  },
  {
    id: 'o2',
    requestId: 'r1',
    carrierId: 'c2',
    vehicleId: 'v3',
    status: 'pending',
    price: 2500,
    currency: 'PLN',
    description: 'Profesjonalny transport autokarem MAN Lion Coach. Najwyższy standard podróży.',
    includedServices: ['WiFi', 'Klimatyzacja', 'Toaleta', 'TV', 'Gniazdka 230V', 'Kawa i herbata'],
    proposedDeparture: new Date('2025-12-15T08:00:00'),
    proposedReturn: new Date('2025-12-15T18:00:00'),
    estimatedDuration: 280,
    validUntil: new Date('2025-11-20T23:59:59'),
    createdAt: new Date('2025-11-15T14:30:00'),
  },
  {
    id: 'o3',
    requestId: 'r1',
    carrierId: 'c3',
    vehicleId: 'v1',
    status: 'pending',
    price: 2650,
    currency: 'PLN',
    description: 'Ekologiczny transport - pojazd hybrydowy. Komfort i troska o środowisko.',
    includedServices: ['WiFi', 'Klimatyzacja', 'Kompensacja CO2'],
    proposedDeparture: new Date('2025-12-15T08:00:00'),
    proposedReturn: new Date('2025-12-15T18:00:00'),
    estimatedDuration: 300,
    validUntil: new Date('2025-11-20T23:59:59'),
    createdAt: new Date('2025-11-15T16:00:00'),
  },
  {
    id: 'o4',
    requestId: 'r2',
    carrierId: 'c1',
    vehicleId: 'v2',
    status: 'rejected',
    price: 350,
    currency: 'PLN',
    description: 'Transfer VW Crafter - idealny dla 8 osób. Wygodne skórzane fotele.',
    includedServices: ['Klimatyzacja', 'Bagażnik', 'Pomoc przy bagażu'],
    proposedDeparture: new Date('2025-12-20T14:30:00'),
    estimatedDuration: 30,
    validUntil: new Date('2025-11-25T23:59:59'),
    createdAt: new Date('2025-11-16T15:00:00'),
  },
  {
    id: 'o5',
    requestId: 'r2',
    carrierId: 'c2',
    vehicleId: 'v4',
    status: 'pending',
    price: 400,
    currency: 'PLN',
    description: 'Ford Transit z WiFi. Szybki i komfortowy transfer.',
    includedServices: ['WiFi', 'Klimatyzacja', 'Woda', 'Czekanie na lot bez dodatkowych opłat'],
    proposedDeparture: new Date('2025-12-20T14:30:00'),
    estimatedDuration: 25,
    validUntil: new Date('2025-11-25T23:59:59'),
    createdAt: new Date('2025-11-16T16:30:00'),
  },
  {
    id: 'o6',
    requestId: 'r3',
    carrierId: 'c1',
    vehicleId: 'v9',
    status: 'expired',
    price: 3500,
    currency: 'PLN',
    description: 'Scania Touring - luksusowy autokar dla dużych grup. Komfort i bezpieczeństwo.',
    includedServices: ['WiFi', 'Klimatyzacja', 'Toaleta', 'TV', 'Gniazdka', 'Bar'],
    proposedDeparture: new Date('2025-11-30T09:00:00'),
    estimatedDuration: 240,
    validUntil: new Date('2025-11-25T23:59:59'),
    createdAt: new Date('2025-11-14T12:00:00'),
  },
  {
    id: 'o7',
    requestId: 'r3',
    carrierId: 'c2',
    vehicleId: 'v3',
    status: 'accepted',
    price: 3200,
    currency: 'PLN',
    description: 'MAN Lion Coach - profesjonalny transport dla kibiców.',
    includedServices: ['WiFi', 'Klimatyzacja', 'Toaleta', 'TV', 'Gniazdka 230V'],
    proposedDeparture: new Date('2025-11-30T09:00:00'),
    estimatedDuration: 240,
    validUntil: new Date('2025-11-25T23:59:59'),
    createdAt: new Date('2025-11-14T10:30:00'),
  },
  {
    id: 'o8',
    requestId: 'r4',
    carrierId: 'c1',
    vehicleId: 'v9',
    status: 'expired',
    price: 5200,
    currency: 'PLN',
    description: 'Scania Touring - wyjazd integracyjny z pełnym komfortem.',
    includedServices: ['WiFi', 'Klimatyzacja', 'Toaleta', 'TV', 'Gniazdka', 'Bar', 'Miejsce na narty'],
    proposedDeparture: new Date('2025-12-22T09:00:00'),
    proposedReturn: new Date('2025-12-24T16:00:00'),
    estimatedDuration: 360,
    validUntil: new Date('2025-11-25T23:59:59'),
    createdAt: new Date('2025-11-16T12:00:00'),
  },
  {
    id: 'o9',
    requestId: 'r4',
    carrierId: 'c2',
    vehicleId: 'v6',
    status: 'pending',
    price: 4900,
    currency: 'PLN',
    description: 'Setra S 516 HD - najwyższa klasa dla wyjazdu firmowego.',
    includedServices: ['WiFi', 'Klimatyzacja', 'Toaleta', 'TV', 'Gniazdka', 'Lodówka', 'DVD'],
    proposedDeparture: new Date('2025-12-22T09:00:00'),
    proposedReturn: new Date('2025-12-24T16:00:00'),
    estimatedDuration: 350,
    validUntil: new Date('2025-11-25T23:59:59'),
    createdAt: new Date('2025-11-16T13:30:00'),
  },
  {
    id: 'o10',
    requestId: 'r5',
    carrierId: 'c1',
    vehicleId: 'v1',
    status: 'rejected',
    price: 850,
    currency: 'PLN',
    description: 'Mercedes Sprinter - komfortowy transfer z lotniska.',
    includedServices: ['WiFi', 'Klimatyzacja', 'Pomoc z bagażem'],
    proposedDeparture: new Date('2025-12-18T15:00:00'),
    estimatedDuration: 120,
    validUntil: new Date('2025-12-15T23:59:59'),
    createdAt: new Date('2025-11-16T17:00:00'),
  },
  {
    id: 'o11',
    requestId: 'r5',
    carrierId: 'c3',
    vehicleId: 'v7',
    status: 'rejected',
    price: 780,
    currency: 'PLN',
    description: 'Nissan e-NV200 - ekologiczny transfer elektryczny.',
    includedServices: ['Klimatyzacja', 'Elektryczny', 'Cichy'],
    proposedDeparture: new Date('2025-12-18T15:00:00'),
    estimatedDuration: 125,
    validUntil: new Date('2025-12-15T23:59:59'),
    createdAt: new Date('2025-11-16T18:00:00'),
  },
  {
    id: 'o12',
    requestId: 'r6',
    carrierId: 'c1',
    vehicleId: 'v1',
    status: 'accepted',
    price: 1650,
    currency: 'PLN',
    description: 'Mercedes Sprinter - bezpieczny transport dla grupy szkolnej.',
    includedServices: ['WiFi', 'Klimatyzacja', 'Monitoring', 'Pasy bezpieczeństwa'],
    proposedDeparture: new Date('2025-11-25T08:00:00'),
    proposedReturn: new Date('2025-11-25T20:00:00'),
    estimatedDuration: 90,
    validUntil: new Date('2025-11-20T23:59:59'),
    createdAt: new Date('2025-11-10T14:00:00'),
  },
  {
    id: 'o13',
    requestId: 'r7',
    carrierId: 'c2',
    vehicleId: 'v4',
    status: 'pending',
    price: 950,
    currency: 'PLN',
    description: 'Ford Transit - wygodny transport dla seniorów.',
    includedServices: ['Klimatyzacja', 'WiFi', 'Wygodne siedzenia', 'Niski próg wejścia'],
    proposedDeparture: new Date('2025-12-28T10:00:00'),
    estimatedDuration: 75,
    validUntil: new Date('2025-12-20T23:59:59'),
    createdAt: new Date('2025-11-17T10:00:00'),
  },
  {
    id: 'o14',
    requestId: 'r7',
    carrierId: 'c3',
    vehicleId: 'v8',
    status: 'pending',
    price: 1100,
    currency: 'PLN',
    description: 'Solaris Urbino Electric - cichy i ekologiczny autobus elektryczny.',
    includedServices: ['Klimatyzacja', 'WiFi', 'USB', 'Elektryczny', 'Bardzo cichy'],
    proposedDeparture: new Date('2025-12-28T10:00:00'),
    estimatedDuration: 80,
    validUntil: new Date('2025-12-20T23:59:59'),
    createdAt: new Date('2025-11-17T11:30:00'),
  },
  {
    id: 'o15',
    requestId: 'r4',
    carrierId: 'c3',
    vehicleId: 'v8',
    status: 'expired',
    price: 5800,
    currency: 'PLN',
    description: 'Solaris Urbino Electric - ekologiczny transport na wyjazd firmowy.',
    includedServices: ['Klimatyzacja', 'WiFi', 'USB', '100% Elektryczny'],
    proposedDeparture: new Date('2025-12-22T09:00:00'),
    proposedReturn: new Date('2025-12-24T16:00:00'),
    estimatedDuration: 380,
    validUntil: new Date('2025-11-18T23:59:59'),
    createdAt: new Date('2025-11-16T09:00:00'),
  },
];

// Helper functions
export const getUserById = (id: string) => users.find((u) => u.id === id);
export const getCarrierById = (id: string) => carriers.find((c) => c.id === id);
export const getVehicleById = (id: string) => vehicles.find((v) => v.id === id);
export const getRequestById = (id: string) => transportRequests.find((r) => r.id === id);
export const getOffersByRequestId = (requestId: string) =>
  offers.filter((o) => o.requestId === requestId);
export const getCarrierByUserId = (userId: string) =>
  carriers.find((c) => c.userId === userId);
